## Creating Tensors

In [1]:
import torch
import math

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


### Random Tensors and Seeding

In [5]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


### Tensor Shapes

In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zero_like_x = torch.zeros_like(x)
print(zero_like_x.shape)
print(zero_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [7]:
some_contants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_contants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


### Tensor Data Types

In [ ]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.0
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[12.3902, 15.0541, 16.8179],
        [17.7174, 14.2091, 18.9694]], dtype=torch.float64)
tensor([[12, 15, 16],
        [17, 14, 18]], dtype=torch.int32)


## Math & Logic with PyTorch Tensors

In [12]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos**2
sqrt2s = twos**0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [15]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [16]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

### In Brief: Tensor Broadcasting

In [20]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)
# (2, 4)
# (1, 4)

print(rand)
print(doubled)

tensor([[0.7545, 0.7746, 0.2330, 0.8441],
        [0.9004, 0.3995, 0.6324, 0.9464]])
tensor([[1.5091, 1.5491, 0.4660, 1.6881],
        [1.8008, 0.7990, 1.2648, 1.8928]])


The rules for broadcasting are:

- Each tensor must have at least one dimension - no empty tensors.

- Comparing the dimension sizes of the two tensors, going from last to first:

- Each dimension must be equal, or

- One of the dimensions must be of size 1, or

- The dimension does not exist in one of the tensors

In [21]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(3, 2)  # (,3,2)
print(b)

c = a * torch.rand(3, 1)  # (,3,1)
print(c)

d = a * torch.rand(1, 2)  # (,1,2)
print(d)

tensor([[[0.0113, 0.5183],
         [0.9807, 0.6545],
         [0.4144, 0.0696]],

        [[0.0113, 0.5183],
         [0.9807, 0.6545],
         [0.4144, 0.0696]],

        [[0.0113, 0.5183],
         [0.9807, 0.6545],
         [0.4144, 0.0696]],

        [[0.0113, 0.5183],
         [0.9807, 0.6545],
         [0.4144, 0.0696]]])
tensor([[[0.4648, 0.4648],
         [0.4491, 0.4491],
         [0.6265, 0.6265]],

        [[0.4648, 0.4648],
         [0.4491, 0.4491],
         [0.6265, 0.6265]],

        [[0.4648, 0.4648],
         [0.4491, 0.4491],
         [0.6265, 0.6265]],

        [[0.4648, 0.4648],
         [0.4491, 0.4491],
         [0.6265, 0.6265]]])
tensor([[[0.9411, 0.4922],
         [0.9411, 0.4922],
         [0.9411, 0.4922]],

        [[0.9411, 0.4922],
         [0.9411, 0.4922],
         [0.9411, 0.4922]],

        [[0.9411, 0.4922],
         [0.9411, 0.4922],
         [0.9411, 0.4922]],

        [[0.9411, 0.4922],
         [0.9411, 0.4922],
         [0.9411, 0.4922]]])


In [22]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)    # dimensions must match last-to-first

c = a * torch.rand(   2, 3) # both 3rd & 2nd dims different

d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

### More Math with Tensors

In [35]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print("Common functions:")
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print("\nSine and arcsine:")
print(angles)
print(sines)
print(inverses)

# bitwise operations
print("\nBitwise XOR:")
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print("\nBroadcasted, element-wise equality comparion:")
d = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
e = torch.ones(1, 2)
print(torch.eq(d, e))

# reductions:
print("\nReduction ops:")
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])))

# vector and linear algebra operations
v1 = torch.tensor([1.0, 0.0, 0.0])
v2 = torch.tensor([0.0, 1.0, 0.0])
m1 = torch.rand(2, 2)
m2 = torch.tensor([[3.0, 0.0], [0.0, 3.0]])
print("\nVectors & Matrices:")
print(torch.linalg.cross(v2, v1))
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)
print(torch.linalg.svd(m3))

Common functions:
tensor([[0.3418, 0.4226, 0.2912, 0.2842],
        [0.3210, 0.6467, 0.4314, 0.2806]])
tensor([[1., -0., -0., -0.],
        [-0., -0., -0., -0.]])
tensor([[ 0., -1., -1., -1.],
        [-1., -1., -1., -1.]])
tensor([[ 0.3418, -0.4226, -0.2912, -0.2842],
        [-0.3210, -0.5000, -0.4314, -0.2806]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparion:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.7207, 0.3541],
        [0.9756, 0.1458]])
tensor([[2.1622, 1.0622],
        [2.9267, 0.4374]])
torch.return_types.linalg_svd(
U=tensor([[-0.6275, -0.7786],
        [-0.7786,  0.6275]]),
S=tensor([3.7725, 0.5734]),
Vh=tensor([[-0.9637, -0.2669],
        [ 0.2669, -0.963

### Altering Tensors in Place

In [42]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print(f"{a=}")
print(torch.sin(a))
print(f"{a=}")

print("")

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print(f"{b=}")
print(b.sin_())
print(f"{b=}")

a=tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
a=tensor([0.0000, 0.7854, 1.5708, 2.3562])

b=tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
b=tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [47]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print("Before:")
print(f"{a=}")
print(f"{b=}")

print("\nAfter add_")
print(f"{a.add_(b)=}")
print(f"{a=}")
print(f"{b=}")

print("\nAfter multiplying")
print(f"{b.mul_(b)=}")
print(f"{b=}")

Before:
a=tensor([[1., 1.],
        [1., 1.]])
b=tensor([[0.8499, 0.0936],
        [0.0243, 0.7260]])

After add_
a.add_(b)=tensor([[1.8499, 1.0936],
        [1.0243, 1.7260]])
a=tensor([[1.8499, 1.0936],
        [1.0243, 1.7260]])
b=tensor([[0.8499, 0.0936],
        [0.0243, 0.7260]])

After multiplying
b.mul_(b)=tensor([[7.2234e-01, 8.7678e-03],
        [5.8815e-04, 5.2703e-01]])
b=tensor([[7.2234e-01, 8.7678e-03],
        [5.8815e-04, 5.2703e-01]])


In [52]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(f"{c=}")
d = torch.matmul(a, b, out=c)
print(f"{c=}")

assert c is d
assert id(c) == old_id

torch.rand(2, 2, out=c)
print(f"{c=}")
assert id(c) == old_id

c=tensor([[0., 0.],
        [0., 0.]])
c=tensor([[0.5609, 0.8926],
        [0.5300, 0.8850]])
c=tensor([[0.1451, 0.1924],
        [0.7354, 0.6377]])


## Copying Tensors

In [54]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561
print(f"{b=}")

b=tensor([[  1., 561.],
        [  1.,   1.]])


In [58]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a
print(torch.eq(a, b))

a[0][1] = 561
print(f"{b=}")

tensor([[True, True],
        [True, True]])
b=tensor([[1., 1.],
        [1., 1.]])


In [60]:
a = torch.rand(2, 2, requires_grad=True)  # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.1598, 0.9081],
        [0.6024, 0.0726]], requires_grad=True)
tensor([[0.1598, 0.9081],
        [0.6024, 0.0726]], grad_fn=<CloneBackward0>)
tensor([[0.1598, 0.9081],
        [0.6024, 0.0726]])
tensor([[0.1598, 0.9081],
        [0.6024, 0.0726]], requires_grad=True)


In [59]:
a = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
b = a.clone()  # requires_grad 继承了 True

# 用 b 参与计算
loss = (b * 2).sum()
loss.backward()

print(f"a.grad: {a.grad}")  # 输出: tensor([2., 2., 2.]) ✅ 有值，且正确
print(f"b.grad: {b.grad}")  # 输出: None ❌ 没有值（非叶子节点被丢弃）

a.grad: tensor([2., 2., 2.])
b.grad: None


/var/folders/mr/9102fbp914dc6mvdxk_pkfmr0000gp/T/ipykernel_45383/2208955437.py:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /Users/runner/work/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:498.)
  print(f"b.grad: {b.grad}")  # 输出: None ❌ 没有值（非叶子节点被丢弃）


In [69]:
import torch

a = torch.rand(2, 2, requires_grad=True)
# 假设 a 已经有了一些梯度（比如反向传播后）
a.sum().backward()  # 让 a.grad 有值（全1矩阵）

# 完全隔离复制
b = a.detach().clone().requires_grad_(True)

# 1. 数值隔离（修改 b 不影响 a）
with torch.no_grad():
    b[0, 0] = 999.0  # ✅ 完全不影响 a，且不报错

print(f"{a=}")  # 输出还是原来的随机数，不受影响 ✅
print(f"{b=}")

# 2. 梯度内存隔离（反向传播各走各的）
loss_b = b.sum()
loss_b.backward()  # 梯度流向 b
print(f"{a.grad=}")      # 依然是之前剩下的全1矩阵，没有叠加新梯度 ✅ 完全隔离
print(f"{b.grad=}")      # 输出: tensor([[1., 1.], [1., 1.]]) ✅ 有值
print(f"{b.grad is a.grad=}")  # False ✅

a=tensor([[0.3922, 0.9516],
        [0.0343, 0.4771]], requires_grad=True)
b=tensor([[9.9900e+02, 9.5156e-01],
        [3.4323e-02, 4.7713e-01]], requires_grad=True)
a.grad=tensor([[1., 1.],
        [1., 1.]])
b.grad=tensor([[1., 1.],
        [1., 1.]])
b.grad is a.grad=False


## Moving to Accelerator

In [71]:
if torch.accelerator.is_available():
    print("We have an accelerator!")
else:
    print("Sorry, CPU only.")

We have an accelerator!


In [72]:
if torch.accelerator.is_available():
    gpu_rand = torch.rand(2, 2, device=torch.accelerator.current_accelerator())
    print(gpu_rand)
else:
    print("Sorry, CPU only.")

tensor([[0.9037, 0.0728],
        [0.9325, 0.4045]], device='mps:0')


In [73]:
my_device = (
    torch.accelerator.current_accelerator()
    if torch.accelerator.is_available()
    else torch.device("cpu")
)
print(f"Device: {my_device}")

x = torch.rand(2, 2, device=my_device)
print(x)

Device: mps
tensor([[0.4754, 0.3793],
        [0.9331, 0.3758]], device='mps:0')


In [74]:
y = torch.rand(2, 2)
y = y.to(my_device)

In [78]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='mps')
z = x + y  # exception will be thrown

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

## Manipulating Tensor Shapes

### Changing the Number of Dimensions

In [81]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [82]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.4938]]]]])


In [84]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)
print(d)

torch.Size([1, 20])
tensor([[0.1914, 0.3617, 0.3090, 0.8108, 0.2137, 0.5729, 0.2990, 0.7758, 0.8474,
         0.9790, 0.8739, 0.1655, 0.9714, 0.3302, 0.0468, 0.2181, 0.2901, 0.6551,
         0.1292, 0.4469]])
torch.Size([20])
tensor([0.1914, 0.3617, 0.3090, 0.8108, 0.2137, 0.5729, 0.2990, 0.7758, 0.8474,
        0.9790, 0.8739, 0.1655, 0.9714, 0.3302, 0.0468, 0.2181, 0.2901, 0.6551,
        0.1292, 0.4469])
torch.Size([2, 2])
torch.Size([2, 2])
tensor([[0.9690, 0.7204],
        [0.4234, 0.2947]])


In [85]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(3, 1)
print(c)

tensor([[[0.8586, 0.8586],
         [0.6513, 0.6513],
         [0.3410, 0.3410]],

        [[0.8586, 0.8586],
         [0.6513, 0.6513],
         [0.3410, 0.3410]],

        [[0.8586, 0.8586],
         [0.6513, 0.6513],
         [0.3410, 0.3410]],

        [[0.8586, 0.8586],
         [0.6513, 0.6513],
         [0.3410, 0.3410]]])


In [87]:
a = torch.ones(4, 3, 2)
b = torch.rand(3)  # (3)
c = b.unsqueeze(1)  # (3,1)
print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.0427, 0.0427],
         [0.9017, 0.9017],
         [0.9755, 0.9755]],

        [[0.0427, 0.0427],
         [0.9017, 0.9017],
         [0.9755, 0.9755]],

        [[0.0427, 0.0427],
         [0.9017, 0.9017],
         [0.9755, 0.9755]],

        [[0.0427, 0.0427],
         [0.9017, 0.9017],
         [0.9755, 0.9755]]])


In [88]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [89]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


## NumPy Bridge

In [91]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [92]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.9175, 0.4375, 0.3398],
        [0.0021, 0.2519, 0.2733]])
[[0.9174995  0.4374935  0.33979625]
 [0.00208318 0.25185794 0.27328575]]


In [93]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[9.1749948e-01 4.3749350e-01 3.3979625e-01]
 [2.0831823e-03 1.7000000e+01 2.7328575e-01]]
