# Automatic Differentiation with `torch.autograd`

In [1]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

![computational graph](https://docs.pytorch.org/tutorials/_images/comp-graph.png)

In [2]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Granient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x10c0225f0>
Granient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x10c085e70>


# Computing Gradients

In [3]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.2912, 0.1755, 0.2416],
        [0.2912, 0.1755, 0.2416],
        [0.2912, 0.1755, 0.2416],
        [0.2912, 0.1755, 0.2416],
        [0.2912, 0.1755, 0.2416]])
tensor([0.2912, 0.1755, 0.2416])


# Disabling Gradient Tracking

In [4]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = x @ w + b
print(z.requires_grad)

True
False


In [5]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


# More on Computational Graphs

# Optional Reading: Tensor Gradients and Jacobian Products

In [14]:
inp = torch.eye(4, 5, requires_grad=True); print(inp)
out = (inp+1).pow(2).t(); print(out)
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], requires_grad=True)
tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<TBackward0>)
First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
